// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcidbflmausrsimubltx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjaWRiZmxtYXVzcnNpbXVibHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODQyNzgsImV4cCI6MjA3MDc2MDI3OH0._kdCzhkJt-oBbtWo5O-uCnsUH4YjHHe5dRWHsYGMa1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});